name: agent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_riverpod: ^3.3.2
  go_router: ^17.3.0
  hooks_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3
  window_manager: ^0.5.2
  freezed_annotation: ^3.0.0
  lucide_icons_flutter: ^3.1.14+2
  xterm2: ^5.0.0
  path: ^1.9.0
  meta: ^1.18.0
  riverpod: ^3.3.2
  flutter_pty_new: ^1.0.0
  nanoid: ^1.0.0
  ansi_strip: ^0.1.1+1
  desktop_drop: ^0.7.1
  streamdown: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.4
  build_runner: ^2.15.0
  riverpod_lint: ^3.1.4
  freezed: ^3.0.0

flutter:
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono/JetBrainsMono-Regular.ttf
    - family: HarmonyOS Sans SC
      fonts:
        - asset: assets/fonts/HarmonyOSSans/HarmonyOS_Sans_SC.ttf
          weight: 400
    - family: HarmonyOS Sans
      fonts:
        - asset: assets/fonts/HarmonyOSSans/HarmonyOS_Sans.ttf
          weight: 400
